services:
  reverse-proxy:
    image: traefik:v3.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yml:ro
      - ./config/traefik_dynamic.yaml:/etc/traefik/traefik_dynamic.yml:ro
    networks:
      - homelab
    environment:
      AWS_ACCESS_KEY_ID: /run/secrets/traefik_aws_access_key_id
      AWS_SECRET_ACCESS_KEY: /run/secrets/traefik_aws_secret_access_key
      AWS_REGION: /run/secrets/traefik_aws_region
      AWS_HOSTED_ZONE_ID: /run/secrets/traefik_aws_hosted_zone_id

networks:
  homelab:
    external: true

secrets:
  traefik_aws_access_key_id:
    external: true
  traefik_aws_secret_access_key:
    external: true
  traefik_aws_region:
    external: true
  traefik_aws_hosted_zone_id:
    external: true