services:
  reverse-proxy:
    image: traefik:v3.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yml:ro
      - ./config/traefik_dynamic.yaml:/etc/traefik/traefik_dynamic.yml:ro
    networks:
      - homelab
    secrets:
      - traefik_aws_credentials

    environment:
      AWS_REGION: eu-west-2
      AWS_HOSTED_ZONE_ID: Z036922937MRC0SUTL5BZ
      AWS_SHARED_CREDENTIALS_FILE: /run/secrets/traefik_aws_credentials

networks:
  homelab:
    external: true

secrets:
  traefik_aws_credentials:
    external: true
