services:
  api:
    container_name: api
    build:
      context: .
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`api.sussexmews.co.uk`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"

networks:
  homelab:
    external: true