services:
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-passwd:/run/secrets/postgres-passwd:ro
    networks:
      - homelab

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sussexmews.co.uk
      - PGADMIN_DEFAULT_PASSWORD=assword
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.sussexmews.co.uk`)"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"

networks:
  homelab:
    external: true

volumes:
  pgdata:
  pgadmin_data: