services:
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-passwd:/run/secrets/postgres-passwd:ro
    networks:
      - homelab

networks:
  homelab:
    external: true

volumes:
  pgdata: