# Dynamic Configuration
http:
  routers:
    dashboard:
      entrypoints:
        - websecure
      rule: Host(`traefik.sussexmews.co.uk`)
      service: api@internal
      middlewares:
        - auth
      tls:
        certResolver: letsencrypt
        domains:
          - main: "sussexmews.co.uk"
            sans:
              - "*.sussexmews.co.uk"

    homebridge:
      entryPoints:
        - websecure
      rule: "Host(`homebridge.sussexmews.co.uk`)"
      service: homebridge
      tls:
        certResolver: letsencrypt

    hyperoptic:
      entryPoints:
        - websecure
      rule: "Host(`hyperoptic.sussexmews.co.uk`)"
      service: hyperoptic
      tls:
        certResolver: letsencrypt

    tplink:
      entryPoints:
        - websecure
      rule: "Host(`tplink.sussexmews.co.uk`)"
      service: tplink
      tls:
        certResolver: letsencrypt

  services:
    homebridge:
      loadBalancer:
        servers:
          - url: "http://192.168.0.200:8581/"

    hyperoptic:
      loadBalancer:
        servers:
          - url: "http://192.168.0.1"

    tplink:
      loadBalancer:
        servers:
          - url: "http://192.168.0.2"


  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$2y$05$fSBrNpileETke85./bllK.evbLLQLo.Kz3wKNNJY7QU1rqtjS8ez2"

