# Dynamic Configuration
http:
  routers:
    dashboard:
      entrypoints:
        - websecure
      rule: Host(`traefik.sussexmews.co.uk`)
      service: api@internal
      middlewares:
        - auth
      tls:
        certResolver: letsencrypt
        domains:
          - main: "sussexmews.co.uk"
            sans:
              - "*.sussexmews.co.uk"

    homebridge:
      entryPoints:
        - websecure
      rule: "Host(`homebridge.sussexmews.co.uk`)"
      service: homebridge-service
      tls:
        certResolver: letsencrypt

services:
  homebridge-service:
    loadBalancer:
      servers:
        - url: "http://192.168.1.117:8581/"

  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$2y$05$fSBrNpileETke85./bllK.evbLLQLo.Kz3wKNNJY7QU1rqtjS8ez2"

