services:
  scanner:
    restart: always
    container_name: tgtg-scanner
    networks:
      - homelab
    image: derhenning/tgtg:latest-alpine    
    environment:
    - TGTG_USERNAME=will.bishop9427@gmail.com
    - SLEEP_TIME=60
    - TZ=Europe/London
    - LOCALE=en_GB
    - DEBUG=true
    - CONSOLE=true

    volumes:
    - ./tokens:/tokens

networks:
  homelab:
    external: true