services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: vpn
    restart: always
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    networks:
      - homelab
    env_file: .env
    volumes:
      - etc_wireguard:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vpn.entrypoints=websecure"
      - "traefik.http.routers.vpn.rule=Host(`vpn.sussexmews.co.uk`)"
      - "traefik.http.routers.vpn.tls=true"
      - "traefik.http.routers.vpn.tls.certresolver=letsencrypt"
      - "traefik.http.services.wg-easy-vpn.loadbalancer.server.port=51821"


volumes:
  etc_wireguard:
    name: vpn-volume

networks:
  homelab:
    external: true