services:
  nginx:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - homelab

networks:
  homelab:
    external: true