services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    networks: 
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homebridge.entrypoints=websecure"
      - "traefik.http.routers.homebridge.rule=Host(`homebridge.sussexmews.co.uk`)"
      - "traefik.http.routers.homebridge.tls=true"
      - "traefik.http.routers.homebridge.tls.certresolver=letsencrypt"

networks:
  homelab:
    external: true