services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    network_mode: host
