name: deploy

on:
  push:
    branches:
      - main

jobs:
  format-and-lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install ruff
        run: uv tool install ruff

      - name: Format
        run: uv run ruff format --check .

      - name: Lint
        run: uv run ruff format --check .

  changes:
    runs-on: self-hosted
    needs: format-and-lint
    outputs:
      traefik: ${{ steps.filter.outputs.traefik }}
      nginx: ${{ steps.filter.outputs.nginx }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          traefik:
            - 'homelab/traefik/**'
          nginx:
            - 'homelab/nginx/**'

  deploy-traefik-config:
    runs-on: self-hosted
    needs: changes
    if: ${{ needs.changes.outputs.traefik == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: deploy
        run: docker stack deploy --resolve-image always --compose-file homelab/traefik/docker-compose.yaml traefik


  deploy-website:
    runs-on: self-hosted
    needs: changes
    if: ${{ needs.changes.outputs.nginx == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: deploy
        run: docker service update --force traefik_reverse-proxy
