name: deploy

on:
  push:
    branches:
      - main

jobs:

  deploy-website:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: deploy
        run: docker stack deploy -c homelab/nginx/docker-compose.yaml nginx
