name: format-and-lint

on:
  pull_request:
    branches:
      - main

jobs:
  format-and-lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install ruff
        run: uv tool install ruff

      - name: Format
        run: uv run ruff format --check .

      - name: Lint
        run: uv run ruff format --check .
