name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - gh-action-runner

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-liner script
        run: echo "Hello, self-hosted runner!"
